export const transactionsData = [
    {
        id: "101",
        category: "Snacks",
        personName: "Ashutosh",
        spentDate: "15th Feb 2024",
        amount: 800.0,
    },
    {
        id: "102",
        category: "Travel",
        personName: "Mangesh",
        spentDate: "1st Feb 2024",
        amount: 3500.0,
    },
    {
        id: "103",
        category: "Materials",
        personName: "",
        spentDate: "15th Jan 2024",
        amount: 5000.0,
    },
    {
        id: "104",
        category: "Snacks",
        personName: "Ashutosh",
        spentDate: "15th Feb 2024",
        amount: 800.0,
    },
    {
        id: "105",
        category: "Travel",
        personName: "Mangesh",
        spentDate: "1st Feb 2024",
        amount: 3500.0,
    },
    {
        id: "106",
        category: "Materials",
        personName: "",
        spentDate: "15th Jan 2024",
        amount: 5000.0,
    },
    {
        id: "107",
        category: "Snacks",
        personName: "Ashutosh",
        spentDate: "15th Feb 2024",
        amount: 800.0,
    },
    {
        id: "108",
        category: "Travel",
        personName: "Mangesh",
        spentDate: "1st Feb 2024",
        amount: 3500.0,
    },
    {
        id: "109",
        category: "Materials",
        personName: "",
        spentDate: "15th Jan 2024",
        amount: 5000.0,
    },
];